---
title: "test_doc"
output: html_document
date: "2026-02-20"
---
```{r}
library(tidyverse)
library(janitor)
```

```{r}
egg_lay <- read.csv("data/egg_laying_data.csv") %>% clean_names()
plant_compo <- read.csv("data/plant_chemistry_data.csv") %>% clean_names()
```

```{r}
glimpse(egg_lay)
```

```{r}
summary(egg_lay)
```

```{r}

```

```{r}
egg_lay %>% 
  ggplot(aes(x = season, fill = season)) +
  geom_bar()
```

```{r}
egg_lay %>% 
  filter(occupied == 1) %>% 
  ggplot(aes(y = n_eggs, x = larvae, colour = season)) +
  geom_point()
```

```{r}
egg_lay %>% 
  ggplot(aes(x = temperature_ambient, y = n_eggs, fill = season)) +
  geom_col()
```

```{r}
egg_lay %>% 
  filter(occupied != 0) %>% 
  ggplot(aes(x = n_eggs, y = log10(average_leaf_size), fill = season)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)+
  facet_grid(season~., labeller = label_both)+
  labs(
    title = "Egg Laying Preference based on Average Leaf Size per Season",
    x = "Number of Eggs per leaf",
    y = "Average Leaf Size (log10 mm^2)"
  )
```
```{r}
egg_lay %>% 
  mutate(occupied = ifelse(occupied == 0, "unoccupied", "occupied")) %>%
  ggplot(aes(x = temperature_soil, y = predicted_n, shape = occupied, color = occupied)) +
  geom_point(size = 1.5)
```

```{r}
```