---
title: "work_arden"
output: html_document
date: "2026-02-25"
---
# Description
Rstudio code to analyze egg laying preferences of butterflies via correlations to ambient temperature and nitrogen content.
```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
```

```{r}
egg_laying <- read_csv("data/egg_laying_data.csv") %>% 
  clean_names()
```

# Ambient Temperature (SCRAPPED DUE TO INCOMPLETE TEMPERATURE RANGE)
```{r}
egg_laying %>%
  select(temperature_ambient, n_eggs) %>% 
  mutate(lay_eggs = if_else(n_eggs > 0, "Yes", "No")) %>%
  ggplot(aes(x = lay_eggs, y = temperature_ambient, fill = lay_eggs)) +
  geom_boxplot() +
  scale_fill_manual(values = c("Yes" = "lightblue", "No" = "orange")) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Egg Presence based on Ambient Temperature",
    x = "Any Eggs?",
    y = "Ambient Temperature (°C)"
    )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = temperature_ambient, y = n_eggs, color = season)) +
  geom_jitter(alpha = 0.4) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal() +
  labs(
    title = "Amount of Butterfly Eggs Layed based on Ambient Temperature",
    x = "Ambient Temperature (°C)",
    y = "Amount of Eggs"
  )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = temperature_ambient)) +
  geom_histogram(aes(y = after_stat(density)), color = "black", fill = "lightgreen") +
  geom_density(color = "red", alpha = 0.4, size = 1.5) +
  labs(
    title = "Distribution of Ambient Temperatures for Plants with Butterfly Eggs",
    x = "Plant Nitrogen Content (Mmol/g)",
    y = "Count"
  )
egg_laying %>% 
  select(temperature_ambient, n_eggs) %>%
  filter(n_eggs != 0) %>% 
  mutate(temperature_ambient = as.factor(temperature_ambient)) %>%
  ggplot(aes(x = temperature_ambient, y = n_eggs, fill = as.numeric(as.character(temperature_ambient)))) +
  geom_boxplot() +
  scale_y_continuous(
    breaks = seq(0, 16, by = 1)  # Tick every 10 units
  ) +
  coord_flip() +
  theme_minimal() +
  scale_fill_gradient(low = "lightblue", high = "darkorange") +
  theme(
    legend.position = "none"
    ) +
  labs(
    title = "Egg Laying Preference based on Ambient Temperature",
    x = "Ambient Temperature (°C)",
    y = "Number of Eggs"
  )
```
# Nitrogen Content
```{r}
egg_laying %>%
  select(predicted_n, n_eggs) %>% 
  mutate(lay_eggs = if_else(n_eggs > 0, "Yes", "No")) %>%
  ggplot(aes(x = lay_eggs, y = predicted_n, fill = lay_eggs)) +
  geom_boxplot() +
  scale_fill_manual(values = c("Yes" = "lightblue", "No" = "orange")) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Egg Laying of Butterfiles based on Nitrogen Content of Plants",
    x = "Any Eggs?",
    y = "Plant Nitrogen Content (Mmol/g)"
    )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = predicted_n)) +
  geom_histogram(aes(y = after_stat(density), group = season), color = "black", fill = "green") +
  geom_density(aes(color = "red"), alpha = 0.4, size = 1.5) +
  facet_grid(~season, labeller = label_both) +
  labs(
    title = "Distribution of Nitrogen Content for Plants with Butterfly Eggs",
    x = "Plant Nitrogen Content (Mmol/g)",
    y = "Count"
  )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = predicted_n, y = n_eggs, color = season)) +
  geom_jitter(alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Amount of Butterfly Eggs Layed based on Nitrogen Content of Plants",
    x = "Plant Nitrogen Content (Mmol/g)",
    y = "Amount of Eggs"
  )
```
# Leaf Size
```{r}
egg_laying %>%
  select(average_leaf_size, n_eggs) %>% 
  mutate(lay_eggs = if_else(n_eggs > 0, "Yes", "No")) %>%
  ggplot(aes(x = lay_eggs, y = average_leaf_size, fill = lay_eggs)) +
  geom_boxplot() +
  scale_fill_manual(values = c("Yes" = "lightblue", "No" = "orange")) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Egg Laying of Butterfiles based on Average Leaf Size",
    x = "Any Eggs?",
    y = "Average Leaf Size (mm^2)"
    )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = average_leaf_size)) +
  geom_histogram(aes(y = after_stat(density)), color = "black", fill = "lightgreen") +
  geom_density(color = "red", alpha = 0.4, size = 1.5) +
  labs(
    title = "Distribution of Average Leaf Sizes for Plants with Butterfly Eggs",
    x = "Average Leaf Size (mm^2)",
    y = "Count"
  )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = average_leaf_size, y = n_eggs, color = season)) +
  geom_jitter(alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Amount of Butterfly Eggs Layed based on Average Leaf Size",
    x = "Average Leaf Size (mm^2)",
    y = "Amount of Eggs"
  )
```
# Vegetation around Plant
```{r}
egg_laying %>%
  select(veg, n_eggs) %>% 
  mutate(lay_eggs = if_else(n_eggs > 0, "Yes", "No")) %>%
  ggplot(aes(x = lay_eggs, y = veg, fill = lay_eggs)) +
  geom_boxplot() +
  scale_fill_manual(values = c("Yes" = "lightblue", "No" = "orange")) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Egg Laying of Butterfiles based on % Vegetation",
    x = "Any Eggs?",
    y = "% Vegetation within 50 cm^2"
    )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = veg, y = n_eggs, color = season)) +
  geom_jitter(alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Amount of Butterfly Eggs Layed based on % Vegetation",
    x = "% Vegetation within 50 cm^2",
    y = "Amount of Eggs"
  )
```
# Bare Ground
```{r}
egg_laying %>%
  select(bare_ground, n_eggs) %>% 
  mutate(lay_eggs = if_else(n_eggs > 0, "Yes", "No")) %>%
  ggplot(aes(x = lay_eggs, y = bare_ground, fill = lay_eggs)) +
  geom_boxplot() +
  scale_fill_manual(values = c("Yes" = "lightblue", "No" = "orange")) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Egg Laying of Butterfiles based on % Bare Ground",
    x = "Any Eggs?",
    y = "% Bare Ground within 50 cm^2"
    )
egg_laying %>%
  filter(n_eggs != 0) %>%
  ggplot(aes(x = bare_ground, y = n_eggs, color = season)) +
  geom_jitter(alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Amount of Butterfly Eggs Layed based on % Bare Ground",
    x = "% Bare Ground within 50 cm^2",
    y = "Amount of Eggs"
  )
```
# Season
```{r}
```