---
title: "work_stanley"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(ggmap)
library(leaflet)
```

```{r}
egg_laying <- read_csv("egg_laying_data.csv") %>% 
  clean_names()
plant_chemistry <- read.csv("plant_chemistry_data.csv") %>%
  clean_names()
```

```{r}
plant_joined <- left_join(egg_laying, plant_chemistry, by="plant_id")
```

```{r}
plant_joined %>% 
  select(temperature_ambient, predicted_n, season.x) %>% 
  na.omit() %>% 
  ggplot(aes(x=season.x, y=predicted_n))+
  geom_boxplot(mapping=aes(fill=season.x))
```

```{r}
 plant_joined %>% 
  ggplot(aes(x=temperature_ambient, color=season.x, fill=season.x))+
  geom_density()
```

```{r}
 plant_joined %>% 
  ggplot(aes(x=temperature_soil, color=season.x, fill=season.x))+
  geom_density()
```

```{r}
plant_joined %>% 
  select(predicted_n, n_molar) %>% 
  ggplot(aes(predicted_n, n_molar))+
  geom_point()
```

```{r}
plant_joined %>% 
  select(occupied, temperature_ambient, season.x) %>% 
  mutate(occupied=factor(occupied)) %>% 
  ggplot(aes(x=occupied))+
  geom_bar(mapping=aes(fill=season.x), color="black", position="dodge")
```

```{r}
plant_joined %>% 
  select(occupied, predicted_n, season.x) %>% 
  mutate(occupied=factor(occupied)) %>% 
  ggplot(aes(x=predicted_n))+
  geom_density(mapping=aes(fill=occupied), position="dodge", alpha=0.5)+
  facet_wrap(~season.x, ncol=2, labeller=label_both)
```

# Do butterflies prefer plants with higher percentage of bare land?

```{r}
egg_laying %>% 
  filter(season=="autumn") %>% 
  na.omit() %>% 
  ggplot(mapping=aes(x=bare_ground, y=temperature_soil))+
  geom_point(mapping=aes(color=season))+
  geom_smooth(method="lm", se=T)
```

```{r}
egg_laying %>% 
  filter(season=="spring") %>% 
  na.omit() %>% 
  ggplot(mapping=aes(x=bare_ground, y=predicted_n))+
  geom_point(mapping=aes(color=season))+
  geom_smooth(method="lm", se=T)
```

```{r}
plant_joined %>% 
  na.omit() %>% 
  mutate(occupied=factor(occupied)) %>% 
  ggplot(mapping=aes(x=bare))+
  geom_bar(mapping=aes(fill=occupied), position="dodge")
```

